[[constraint]]
  name = "github.com/cloudfoundry-community/go-cfclient"
  revision = "16c98753d3152f9d80d3c121523536858095a3da"

[[constraint]]
  name = "github.com/cloudfoundry/noaa"
  version = "2.1.0"

[[constraint]]
  name = "github.com/cloudfoundry/sonde-go"
  revision = "b33733203bb48d7c56de7cb639d77f78b0449d19"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/wavefronthq/wavefront-sdk-go"
  version = "0.9.2"

[[constraint]]
  name = "github.com/wavefronthq/go-metrics-wavefront"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gobwas/glob"
  version = "0.2.3"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.1.0"

[prune]
  go-tests = true
  unused-packages = true
